Bug_Tracker_Web/Models/ErrorViewModel.cs
namespace Bug_Tracker_Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }

}

Bug_Tracker_Web/Models/Projects.cs
using System.ComponentModel.DataAnnotations;


namespace Bug_Tracker_Web.Models
{
    public class Projects
    { 

        // Admines : have to be key 
        // Status
        // Testers

        [Key]
        public int Id { get; set; }
        [StringLength(200)]
        public string? Name { get; set; }
        [Display(Name="Date of cration")]
        public DateTime DateOfCreation { get; set; }= DateTime.Now;
        public string? Description { get; set; }
        public string? Status { get; set; }
        
    }
}

Bug_Tracker_Web/Models/Tickets.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Bug_Tracker_Web.Models
{
    public class Tickets
    {
        [Key]
        //[DatabaseGenerated(DatabaseGeneratedOption.None)]
        //[DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public string Issue { get; set; }
        public string Description { get; set; }
        public string Priority { get; set; }
        public DateTime Create { get; set; } = DateTime.Now;
        //[Required]
        public string Owner { get; set; } = "def";
        [Required]
        public string? Assignee { get; set; }
        public DateTime Resolved { get; set; }
        [Required]
        public string? Status { get; set; }
        public string? Attachments { get; set; }
        public string? Comments { get; set; }
        [ForeignKey("ProjectId")]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ProjectId { get; set; } = 1;
    }
}

Bug_Tracker_Web/Models/ViewModelBase.cs
namespace Bug_Tracker_Web.Models
{
    public class ViewModelBase
    {
        public List<string> ProjectsNames { get; set; }
    }
}

Bug_Tracker_Web/Controllers/HomeController.cs
using Bug_Tracker_Web.Data;
using Bug_Tracker_Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bug_Tracker_Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            _db = db;
        }


        public IActionResult Index()
        {
            return this.View();
        }
        //public IActionResult Mathode()
        //{
        //    List<Projects> objCategoryList = _db.Projects.ToList();
        //    return PartialView(objCategoryList);
        //}

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Bug_Tracker_Web/Controllers/ProjectsController.cs
using Bug_Tracker_Web.Data;
using Bug_Tracker_Web.Models;
using Microsoft.AspNetCore.Mvc;

//test for git

namespace Bug_Tracker_Web.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ProjectsController(ApplicationDbContext db) // here i can access what is in the container! 
        {
            _db = db;
        }
        // GET: CategoryController
        public ActionResult Index()
        {
            List<Projects> objProjectsList = _db.Projects.ToList();
            //ViewData["WalidData"] = objProjectsList;
            return View(objProjectsList);
        }
    }
}

Bug_Tracker_Web/Controllers/TicketsController.cs
using Bug_Tracker_Web.Data;
using Bug_Tracker_Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Bug_Tracker_Web.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _db;


        public TicketsController(ApplicationDbContext db) // here i can access what is in the container! 
        {
            _db = db;
        }

        // GET: CategoryController
        public ActionResult Index(int Id)
        {
            if (Id == null || Id ==0)
            {
                return NotFound();
            }

            var ProjectFromDb = _db.Projects.Find(Id);

            ViewBag.Status = ProjectFromDb.Status;
            ViewBag.Date = ProjectFromDb.DateOfCreation.ToString().Split(" ")[0];
            ViewData["WalidData"] = "SalamoAlaikom test!";
            ViewBag.ProjectId = Id;

            // Select from the Tickets only the ones related to the sent project
            List<Tickets> TicketsList = _db.Tickets.Where(b => b.ProjectId == Id).ToList();

            return View(TicketsList);
        }

        // GET
        //lorsque je mettais une autre appelation cela n'a pas marché !!
        // the ansewer : //https://stackoverflow.com/questions/155864/asp-net-mvc-passing-parameters-to-the-controller
        public ActionResult Create(int Id)  
        {
            Console.WriteLine($"The Id i'm getting is {Id}");
            ViewBag.ProjectId = Id;
            return View();
        }

        //// POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken] // to avoid Cross Site Requist Forgery...
        public ActionResult Create(Tickets obj)
        {
            if (obj.Priority != "1" && obj.Priority != "2" && obj.Priority !="3")
            {
                ModelState.AddModelError("CustomError", "the priority is not valid you should enter 1, 2 or 3");
            }
            if (ModelState.IsValid)
            {
                _db.Tickets.Add(obj);
                Console.WriteLine("the issu is : " + obj.Issue);
                Console.WriteLine("the Id is "+obj.Id);
                Console.WriteLine("the Description is "+obj.Description);
                Console.WriteLine("the owner is "+obj.Owner);
                Console.WriteLine("the date of Creation is " + obj.Create);
                Console.WriteLine("the project Id is " + obj.ProjectId);
                _db.SaveChanges();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        /*
        // GET
        public ActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Tickets.Find(id);

            if(categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }
        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken] // to avoid Cross Site Requist Forgery...
        public ActionResult Edit(Tickets obj)
        {
            if (obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("CustomError", "wa sir tqaewd rahoum fhal fhal.");
            }
            if (ModelState.IsValid)
            {
                _db.Tickets.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Category updated successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // GET
        public ActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var categoryFromDb = _db.Tickets.Find(id);

            if (categoryFromDb == null)
            {
                return NotFound();
            }

            return View(categoryFromDb);
        }
        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken] // to avoid Cross Site Requist Forgery...
        public ActionResult DeletePOST(int? id)
        {
            var obj = _db.Tickets.Find(id);
            if(obj == null)
            {
                return NotFound();
            }
            _db.Tickets.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Category deleted successfully";
            return RedirectToAction("Index");
            
        }
        */

    }
}

Bug_Tracker_Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    ViewData["ProjectsNames"] = "wakwak";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>Application developped by BENHAMED Walid :) </p>
</div>

Bug_Tracker_Web/Views/Projects/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@model List<Projects>
@{
    ViewData["Title"] = "Projects";
}

<div class="row">
    <div class="border p-3 mt-4">
        <div class="container p-3">
        <div class="row pt-4">
            <div class="col-6">
                <h2 class="text-primary">Projects</h2>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Projects" asp-action="Create" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> &nbsp; Create New Project
                </a>
            </div>
        </div>
        <br /><br />

    <table class="table table-b table-striped" style="width:100%">
        <thead class="thead-dark">
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Date of creation
                </th>
                <th>
                    Description
                </th>
                <th>
                    Status
                </th>
            </tr>
        </thead>

    <tbody>
            @foreach(var obj in Model)
            {
                <tr>  
                    <td width="20%">
                        @obj.Name
                    </td>
                    <td width="18%">
                        @obj.DateOfCreation.ToString().Split(" ")[0]
                    </td>
                    <td width="20%">
                        @obj.Description
                    </td>
                    <td width="18%">
                        @obj.Status
                    </td>
                    <td width="24%">
                        <div class="w-10 btn btn-rouge" role="group">

                            <a asp-controller="Tickets" asp-action="Index" asp-route-id="@obj.Id"
                            style="width:80px" class="btn btn-success">Open</a>

                            <a asp-controller="Projects" asp-action="Index" asp-route-id="@obj.Id"
                            style="width:80px" class="btn btn-primary">Edit</a>

                            <a asp-controller="Projects" asp-action="Index" asp-route-id="@obj.Id"
                            style="width:80px" class="btn btn-danger">Delete</a>

                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>
    <div/>
<div/>

</div>

Bug_Tracker_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bug_Tracker_Web</title>
    <link rel="stylesheet" href="~/css/bootswatchTheam.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bug_Tracker_Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
       
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Bug_Tracker</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                @*<li class="nav-item dropdown">
                    <a class="nav-link" asp-area="" asp-controller="Tickets" asp-action="Index">Projects</a>
                </li>*@
       
                @*<li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Projects</a>
                  <div class="dropdown-menu">
                        @{
                                    for (int i=0;i<3;i++)
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="Tickets" asp-action="Index">@ViewData["ProjectsNames"]</a>
                                    }
                                }
                    <a class="dropdown-item" href="#">HHHHHH</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#"><i class="bg bi-plus-circle"></i>&nbsp; Add project</a>
                  </div>
                </li>*@
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                </li>
              </ul>
              <form class="d-flex">
                <input class="form-control me-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"/>
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container-fluid">
            &copy; 2022 - Bug_Tracker_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Bug_Tracker_Web/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        *toastr.error('@TempData["error"]');
    </script>
} 

Bug_Tracker_Web/Views/Tickets/Create.cshtml
@model Tickets

<form method="post">
    <div class="row border p-3 mt-4">
        
        <div class="row pb-2">
            <h2 class="col-12 text-primary">Create a ticket</h2>
        </div>

        <div class="row pb-2">
            @*<div asp-validation-summary = "All"></div>*@
            <div class="col-4">
                <div class="mb-3">
                    <label asp-for="Issue"></label>
                    <input asp-for="Issue" class="form-control" />
                    <span asp-validation-for="Issue" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for ="Priority"></label>
                    <input asp-for="Priority" class="form-control" />
                    <span asp-validation-for="Priority" class="text-danger"></span>
                </div>
                @*<div class="mb-3">
                    <label asp-for ="Owner"></label>
                    <input asp-for="Owner" class="form-control" />
                    <span asp-validation-for="Owner" class="text-danger"></span>
                </div>*@
                <div class="mb-3">
                    <label asp-for ="Assignee"></label>
                    <input asp-for="Assignee" class="form-control" />
                    <span asp-validation-for="Assignee" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label asp-for ="Status"></label>
                    <input asp-for="Status" class="form-control" />
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
            </div>

            <div class="col-8">
                <div class="form-group mb-3">
                    <label asp-for="Description">Description</label>
                    <textarea asp-for="Description" class="form-control" rows="3" style="height: 194px; resize:none;"></textarea>
                    @*<label for="exampleTextarea" class="form-label mt-4">Example textarea</label>
                    <textarea class="form-control" id="exampleTextarea" rows="3" style="height: 150px;"></textarea>*@
                </div>

                @*<div class="form-gourp mb-3">
                    <label asp-for="Attachments"></label>
                    <input asp-for="Attachments" class="form-control" type="file" id="formFile">
                </div>*@
            </div>

            <div class="row">
                <div class="form-gourp pt-4 text-center">
                    @*The Create button here is directly linked to the tag helpers -> i still need to understand why and how!?*@
                    <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                    <a asp-controller="Tickets" asp-action="Index" asp-route-id="@ViewBag.ProjectId" class="btn btn-secondary" style ="width:150px">
                        Back to List
                    </a>
                </div>
            </div>
            
        </div>

        @*<div class="row">
            
            <div class="col-6">
                <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
                <a asp-controller="Tickets" asp-action="Index" asp-route-id="@ViewBag.ProjectId" class="btn btn-secondary" style ="width:150px">
                    Back to List
                </a>
            </div>
        </div>*@
    
    </div>
</form>
@section Scripts{
    @{
    <partial name="_ValidationScriptsPartial" />
    }
}

Bug_Tracker_Web/Views/Tickets/Index.cshtml
@model List<Tickets>
@*@model Tickets*@
@{
    ViewData["Title"] = "Projects";
    ViewData["ProjectsNames"] = "hhhhhh";
    //ViewData["ProjectId"] = ViewBag.Id;
}

<div class="row">
    <div class="border p-3 mt-4 col-5">
        <div class="row pb-2">
            <h2 class="text-primary">@ViewBag.Name</h2>
        </div>
        <div class="row">
            <div class="col-6">
                <label class="text-primary">Admins</Label>
            </div>
            <div class="col-6">
                <label class="text-primary">Testers</label>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <label class="text-secondary p-1 mt-1">Benhamed Walid</Label>
            </div>
            <div class="col-6">
                <label class="text-secondary p-1 mt-1">Benhamed Walid & Niolas charles</</label>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-6">
                <label class="text-primary">Status</Label>
            </div>
            <div class="col-6">
                <label class="text-primary">Opening Date</label>
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <label class="text-primary">
                    <label class="text-secondary p-1 mt-1">@ViewBag.Status</label>
                </Label>
            </div>
            <div class="col-6">
                <label class="text-secondary p-1 mt-1">@ViewBag.Date</</label>
            </div>
        </div>
        @*<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-controller="Tickets" asp-action="Index" class="btn btn-secondary" style ="width:150px">
            Back to List
        </a>*@
    </div>
    <div class="p-3 mt-4 col-1"></div>
    <div class="border p-3 mt-4 col-6">
        <p class="p-4 mt-5">Bonjour Sur mon application Bug Tracker, nous somme le @DateTime.Now</p>
    </div>
</div>

<div class="row">
    <div class="border p-3 mt-4">
        <div class="container p-3">
        <div class="row pt-4">
            <div class="col-6">
                <h2 class="text-primary">Tickets List</h2>
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Tickets" asp-action="Create" asp-route-id="@ViewBag.ProjectId" class="btn btn-primary">
                    <i class="bi bi-plus-circle"></i> &nbsp; Create New Ticket 
                </a>
            </div>
        </div>
        <br /><br />

    <table class="table table-b table-striped" style="width:100%">
        <thead class="thead-dark">
            <tr>
                <th>
                    Issue
                </th>
                <th>
                    Priority
                </th>
                <th>
                    Date of creation
                </th>
                <th>
                    Owner
                </th>
                <th>
                    Assignee
                </th>
                <th>
                    Resolved
                </th>
                <th>
                    Status
                </th>
                @*<th>
                    Attatchments
                </th>*@
                @*<th>
                    Comments
                </th>*@
                <th/>
            </tr>
        </thead>

    <tbody>
            @foreach(var obj in Model)
            {
                <tr>  
                    <td width="11%">
                        @obj.Issue
                    </td>
                    <td width="11%">
                        @obj.Priority
                    </td>
                    <td width="11%">
                        @obj.Create.ToString().Split(" ")[0]
                    </td>
                    <td width="11%">
                        @obj.Owner
                    </td>
                    <td width="11%">
                        @obj.Assignee
                    </td>
                    <td width="11%">
                        @obj.Resolved.ToString().Split(" ")[0]
                    </td>
                    <td width="11%">
                        @obj.Status
                    </td>
                    @*<td width="11%">
                        @obj.Attachments
                    </td>
                    <td width="11%">
                        @obj.Comments
                    </td>*@
                    <td>
                        <div class="w-10 btn btn-rouge" role="group">
                            <a asp-controller="Tickets" asp-action="Index" asp-route-id="@obj.Id"
                            class="btn btn-primary">Edit</a>

                            <a asp-controller="Tickets" asp-action="Index" asp-route-id="@obj.Id"
                            class="btn btn-danger">Delete</a>

                        </div>
                    </td>
                </tr>
            }
        </tbody>

    @*    <tbody>
            @foreach(var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Issue
                    </td>
                    <td width="30%">
                        @obj.Priority
                    </td>
                    <td>
                        <div class="w-100 btn-group" role="group">

                            <a asp-controller="Category" asp-action="edit" asp-route-id="@obj.Id"
                            class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i> &nbsp; Edit</a>

                            <a asp-controller="Category" asp-action="Delete" asp-route-id="@obj.Id"
                            class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> &nbsp; Delete</a>

                        </div>
                    </td>
                </tr>
            }
        </tbody>*@

    </table>
    <div/>
<div/>

</div>